In [8]:
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import math
import numpy as np
import matplotlib.pyplot as plt
from pandas import read_csv

In [15]:
dataframe = read_csv('/Users/gimseung-yeon/연습/deeplearning/corona_daily.csv', usecols=[3], engine='python', skipfooter=3)
dataset=dataframe.values
dataset=dataset.astype('float')
dataset

array([[   24.],
       [   24.],
       [   27.],
       [   27.],
       [   28.],
       [   28.],
       [   28.],
       [   28.],
       [   28.],
       [   29.],
       [   30.],
       [   31.],
       [   51.],
       [  104.],
       [  204.],
       [  433.],
       [  602.],
       [  833.],
       [  977.],
       [ 1261.],
       [ 1766.],
       [ 2337.],
       [ 3150.],
       [ 3736.],
       [ 4212.],
       [ 4812.],
       [ 5328.],
       [ 5766.],
       [ 6284.],
       [ 6767.],
       [ 7134.],
       [ 7382.],
       [ 7513.],
       [ 7755.],
       [ 7869.],
       [ 7979.],
       [ 8086.],
       [ 8162.],
       [ 8236.],
       [ 8320.],
       [ 8413.],
       [ 8565.],
       [ 8652.],
       [ 8799.],
       [ 8897.],
       [ 8961.],
       [ 9037.],
       [ 9137.],
       [ 9241.],
       [ 9332.],
       [ 9478.],
       [ 9583.],
       [ 9661.],
       [ 9786.],
       [ 9887.],
       [ 9976.],
       [10062.],
       [10156.],
       [10237.

In [26]:
scaler=MinMaxScaler(feature_range=(0,1))
dataset1=scaler.fit_transform(dataset) #정규화완료
#훈련, 검증 셋으로 나누기
train, test=train_test_split(dataset1, test_size=0.2, shuffle=False)

In [35]:
train[0][0]

0.0

In [44]:
#데이터셋 넣었을때 123->4, 234->5 예측하게 만들기 100 0~96, 99
def 전처리(dataset, lookback):
    입력값=[]
    출력값=[]
    for i in range(len(dataset)-lookback):
        입력값.append(dataset[i:(i+lookback),0])
        출력값.append(dataset[i+lookback,0])
    return np.array(입력값), np.array(출력값)

In [53]:
# train, test dataset 만들기
look_back=3
x_train, y_train = 전처리(train,look_back)
x_test, y_test = 전처리(test,look_back)
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(86, 3) (86,) (20, 3) (20,)


In [52]:
X_train= np.reshape(x_train, (x_train.shape[0], 1, x_train.shape[1]))
X_test= np.reshape(x_test, (x_test.shape[0], 1, x_test.shape[1]))
print(X_train.shape, X_test.shape)

(86, 1, 3) (20, 1, 3)


In [54]:
model=Sequential()
model.add(SimpleRNN(3, input_shape=(1, look_back)))
model.add(Dense(1, activation='linear'))
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 21        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 25 (100.00 Byte)
Trainable params: 25 (100.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [55]:
model.fit(X_train, y_train, batch_size=1, verbose=1, epochs=100)

Epoch 1/100
86/86 [==============================] - 0s 433us/step - loss: 0.4160
Epoch 2/100
86/86 [==============================] - 0s 306us/step - loss: 0.0903
Epoch 3/100
86/86 [==============================] - 0s 300us/step - loss: 0.0303
Epoch 4/100
86/86 [==============================] - 0s 312us/step - loss: 0.0202
Epoch 5/100
86/86 [==============================] - 0s 318us/step - loss: 0.0150
Epoch 6/100
86/86 [==============================] - 0s 305us/step - loss: 0.0107
Epoch 7/100
86/86 [==============================] - 0s 325us/step - loss: 0.0074
Epoch 8/100
86/86 [==============================] - 0s 307us/step - loss: 0.0049
Epoch 9/100
86/86 [==============================] - 0s 305us/step - loss: 0.0032
Epoch 10/100
86/86 [==============================] - 0s 494us/step - loss: 0.0021
Epoch 11/100
86/86 [==============================] - 0s 315us/step - loss: 0.0014
Epoch 12/100
86/86 [==============================] - 0s 299us/step - loss: 9.4603e-04
Epoch 13/

In [64]:
trainPredict=model.predict(X_train)
testPredict=model.predict(X_test)
#train과 test가 예측한 값과 실제값 확인하기
trainPredict1=scaler.inverse_transform(trainPredict)
Y_train = scaler.inverse_transform([y_train])

3/3 [==============================] - 0s 886us/step


1/1 [==============================] - 0s 9ms/step


In [65]:
[y_train]

[array([2.65017668e-04, 3.53356890e-04, 3.53356890e-04, 3.53356890e-04,
        3.53356890e-04, 3.53356890e-04, 4.41696113e-04, 5.30035336e-04,
        6.18374558e-04, 2.38515901e-03, 7.06713781e-03, 1.59010601e-02,
        3.61307420e-02, 5.10600707e-02, 7.14664311e-02, 8.41872792e-02,
        1.09275618e-01, 1.53886926e-01, 2.04328622e-01, 2.76148410e-01,
        3.27915194e-01, 3.69964664e-01, 4.22968198e-01, 4.68551237e-01,
        5.07243816e-01, 5.53003534e-01, 5.95671378e-01, 6.28091873e-01,
        6.50000000e-01, 6.61572438e-01, 6.82950530e-01, 6.93021201e-01,
        7.02738516e-01, 7.12190813e-01, 7.18904594e-01, 7.25441696e-01,
        7.32862191e-01, 7.41077739e-01, 7.54505300e-01, 7.62190813e-01,
        7.75176678e-01, 7.83833922e-01, 7.89487633e-01, 7.96201413e-01,
        8.05035336e-01, 8.14222615e-01, 8.22261484e-01, 8.35159011e-01,
        8.44434629e-01, 8.51325088e-01, 8.62367491e-01, 8.71289753e-01,
        8.79151943e-01, 8.86749117e-01, 8.95053004e-01, 9.022084

In [66]:

Y_train.astype('int')

array([[   27,    28,    28,    28,    28,    28,    29,    30,    31,
           51,   104,   204,   433,   602,   832,   977,  1260,  1766,
         2337,  3150,  3736,  4212,  4812,  5328,  5766,  6283,  6767,
         7134,  7382,  7513,  7755,  7868,  7979,  8086,  8162,  8236,
         8320,  8413,  8565,  8652,  8799,  8897,  8961,  9037,  9137,
         9241,  9332,  9478,  9583,  9661,  9786,  9887,  9976, 10062,
        10156, 10237, 10284, 10331, 10384, 10423, 10450, 10480, 10512,
        10537, 10564, 10591, 10613, 10635, 10653, 10661, 10674, 10683,
        10694, 10702, 10708, 10718, 10728, 10738, 10752, 10761, 10765,
        10774, 10780, 10793, 10801, 10804]])

In [67]:
trainPredict1.astype('int')

array([[  144],
       [  144],
       [  146],
       [  146],
       [  146],
       [  146],
       [  146],
       [  147],
       [  148],
       [  149],
       [  168],
       [  218],
       [  316],
       [  542],
       [  714],
       [  970],
       [ 1130],
       [ 1439],
       [ 1936],
       [ 2508],
       [ 3335],
       [ 3939],
       [ 4498],
       [ 5119],
       [ 5623],
       [ 6086],
       [ 6594],
       [ 7037],
       [ 7404],
       [ 7678],
       [ 7844],
       [ 8076],
       [ 8168],
       [ 8299],
       [ 8395],
       [ 8467],
       [ 8540],
       [ 8612],
       [ 8688],
       [ 8808],
       [ 8875],
       [ 9009],
       [ 9082],
       [ 9154],
       [ 9225],
       [ 9301],
       [ 9379],
       [ 9454],
       [ 9568],
       [ 9642],
       [ 9720],
       [ 9820],
       [ 9890],
       [ 9968],
       [10039],
       [10111],
       [10173],
       [10218],
       [10264],
       [10304],
       [10333],
       [10360],
       [